### PR TITLE
fix: correctly merge command class prototypes

### LINKED ISSUE #764: `args` are stripped away when using the global `--json` flag
**Describe the bug**
When outputting commands with the `--json` flag, all commands that extend a base class show empty `args`. 
**note** commenting out [this line](https://github.com/oclif/plugin-commands/blob/main/src/commands/commands.ts#L164) fixes the problem.

**To Reproduce**

1. Download and install the latest [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli)
2. run `heroku commands --json > herokuCommands.json`
3. Open the herokuCommands.json in an editor or IDE
4. Observe all but 7 commands show `"args": {}`

**Expected behavior**
`args` should not be stripped away. Currently, the Heroku CLI should have 200+ commands with args. 

**Additional context**
This problem seems to occur for all commands that extend a base class. ~~This defect also seems to omit `ARGUMENTS` from the documentation creation process when oclif is used to produce docs.~~ After digging, the doc creation process does not use the affected code branch mentioned here. This problem is limited to the json output.

### PR DESCRIPTION
**Pull request by mdonnalley**
Correctly merge static properties up the Command class inheritance chain. Inspired by oclif/core's [implementation](https://github.com/oclif/core/blob/4.0.23/src/util/cache-command.ts#L12)

Fixes #764 
@W-16844507@

### CODE REVIEW

**Comment by justinwilaby** [comment]
@mdonnalley - Can this be backported down to version 2.x so us dinosaurs can benefit from this fix?

**Comment by mdonnalley** [comment]
@justinwilaby you might be able to ship the heroku cli with plugin-commands v4 without issue. I tested `heroku plugins:install @oclif/plugin-commands@^4` and it seems to be working as expected

**Comment by justinwilaby** [comment]
> @justinwilaby you might be able to ship the heroku cli with plugin-commands v4 without issue. I tested `heroku plugins:install @oclif/plugin-commands@^4` and it seems to be working as expected

If so, can we use `peerDependencies` to specify a range of compatible `@oclif/core` versions?

**Comment by mdonnalley** [comment]
>If so, can this package use peerDependencies to specify a range of compatible @oclif/core versions?

We can but the acceptable range is `all of them` - I'm not sure there'd but much value to it. In fact it would probably work even if heroku used the old oclif libraries instead of `@oclif/core`

**Comment by justinwilaby** [comment]
> We can but the acceptable range is `all of them` - I'm not sure there'd but much value to it. In fact it would probably work even if heroku used the old oclif libraries instead of `@oclif/core`

Great! I suppose the value in the version range would be that implementors would not have yet another version of oclif core installed. The Heroku CLI currently has 3 versions of oclif core in it's dependency tree because of various plugins pinning the version to this one or that one. A version range would prevent this.

**Review by shetzel — APPROVED** [review]

**Comment by shetzel** [comment]
QA: with your PR branch I now see args such as this for the `addons rename` command:
```
"args": {
      "addon_name": {
        "name": "addon_name",
        "required": true
      },
      "new_name": {
        "name": "new_name",
        "required": true
      }
    }
```

**Pull request merged**
